version: "3.8"

services:

  server:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./airflow:/home/airflow
      - ./scraper:/home/scraper
      - ./web:/home/web
      - ./settings:/home/settings
    command: php -S 0.0.0.0:8000 -t /home/web
    networks:
      - internal_conn

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./databases/mariadb:/var/lib/mysql
    networks:
      - internal_conn

  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports: 
      - "8081:80"
    environment:
      PMA_HOST: mariadb
    networks:
      - internal_conn

networks:
  internal_conn:
      driver: bridge